//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 12/02/2016 11:51:11
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace KeePass.Win
{
    using Windows.ApplicationModel.Resources;
    
    
    internal partial class LocalizedStrings
    {
        
        private static ResourceLoader resourceLoader;
        
        static LocalizedStrings()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(LocalizedStrings).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("LocalizedStrings");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/LocalizedStrings");
            }
        }
 
        /// <summary>
        /// Localized resource similar to "Invalid credentials"
        /// </summary>
        public static string InvalidCredentials
        {
            get
            {
                return resourceLoader.GetString("InvalidCredentials");
            }
        }

        /// <summary>
        /// Localized resource similar to "Could not open file"
        /// </summary>
        public static string MenuItemOpenError
        {
            get
            {
                return resourceLoader.GetString("MenuItemOpenError");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "The database you selected is already available."
        /// </summary>
        public static string MenuItemOpenSameFileContent
        {
            get
            {
                return resourceLoader.GetString("MenuItemOpenSameFileContent");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Database already open!"
        /// </summary>
        public static string MenuItemOpenSameFileTitle
        {
            get
            {
                return resourceLoader.GetString("MenuItemOpenSameFileTitle");
            }
        }
    }
}
